%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\xjk374\MATLAB Drive\Load_Flow\Load_Flow_Simulink_v2\cyme_network_9bus_v17\spot loads.xlsx
%    Worksheet: Custom 9
%
% Auto-generated by MATLAB on 16-Dec-2022 01:58:47

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Custom 9";
opts.DataRange = "A2:H8";

% Specify column names and types
opts.VariableNames = ["FromNode", "SpotType", "SpotKWAkW", "SpotKvarAkvar", "SpotKWBkW", "SpotKvarBkvar", "SpotKWCkW", "SpotKvarCkvar"];
opts.VariableTypes = ["string", "categorical", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "FromNode", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["FromNode", "SpotType"], "EmptyFieldRule", "auto");

% Import the data
spotloads = readtable("C:\Users\xjk374\MATLAB Drive\Load_Flow\Load_Flow_Simulink_v2\cyme_network_9bus_v17\spot loads.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts