%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\xjk374\MATLAB Drive\Load_Flow\Load_Flow_Simulink_v2\cyme_network_9bus_v17\Overhead Lines Report.xlsx
%    Worksheet: OverheadLines
%
% Auto-generated by MATLAB on 15-Dec-2022 14:16:24

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 32);

% Specify sheet and range
opts.Sheet = "OverheadLines";
opts.DataRange = "A2:AF9";

% Specify column names and types
opts.VariableNames = ["NetworkId", "SectionId", "EquipmentId", "LineId", "Status", "Phase", "FromNode", "ToNode", "Lengthft", "RatedCurrentAA", "RatedCurrentBA", "RatedCurrentCA", "CondA", "CondB", "CondC", "Neutral1", "Spacing", "LineRAohms", "LineXAohms", "LineBAS", "LineRBohms", "LineXBohms", "LineBBS", "LineRCohms", "LineXCohms", "LineBCS", "LineRmohms", "LineXmohms", "LineBmS", "LineX1ohms", "LineR1ohms", "LineB1S"];
opts.VariableTypes = ["categorical", "string", "categorical", "categorical", "categorical", "categorical", "string", "string", "double", "double", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["SectionId", "FromNode", "ToNode"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["NetworkId", "SectionId", "EquipmentId", "LineId", "Status", "Phase", "FromNode", "ToNode", "CondA", "CondB", "CondC", "Neutral1", "Spacing"], "EmptyFieldRule", "auto");

% Import the data
OverheadLinesReport = readtable("C:\Users\xjk374\MATLAB Drive\Load_Flow\Load_Flow_Simulink_v2\cyme_network_9bus_v17\Overhead Lines Report.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts